---
"name": Trivy Full Scan

"on":
  pull_request:
    branches:
      - main

jobs:
  trivy-full-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Full Trivy Check (optional check)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: fs
          ignore-unfixed: false
          scan-ref: ${{ github.workspace }}
          trivy-config: ${{ github.workspace }}/trivy.yaml
          severity: LOW,MEDIUM,HIGH,CRITICAL
          exit-code: 1